/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rpc_proxy_constants.h"

namespace rpc {

const rpc_proxyConstants g_rpc_proxy_constants;

rpc_proxyConstants::rpc_proxyConstants() {
}

} // namespace

