/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rpc_proxy_CONSTANTS_H
#define rpc_proxy_CONSTANTS_H

#include "rpc_proxy_types.h"

namespace rpc {

class rpc_proxyConstants {
 public:
  rpc_proxyConstants();

};

extern const rpc_proxyConstants g_rpc_proxy_constants;

} // namespace

#endif
